[package]
name = "libhi-ffi"
version = "0.3.0"
workspace = ".."
edition = "2024"

[lib]
name = "hiffi"
path = "src/capi.rs"
crate-type = ["cdylib"]

[dependencies]
libhi = { path = ".." }

[build-dependencies]
cbindgen = "0.28.0"
